#!/usr/bin/env python3
import os
from os.path import expanduser
import sys


bash_profile = expanduser("~/.bashrc")
synthetic_directory = os.getcwd()
ue4_root = sys.argv[1]

print("UE4_SYNTHETIC: {}".format(synthetic_directory))
print("UE4_ROOT: {}".format(ue4_root))

export_ue4_root = "export UE4_ROOT={}".format(ue4_root)
export_synthetic = "export UE4_SYNTHETIC={}".format(synthetic_directory)

def write_string(string, bash_file):
    with open(bash_file, "r") as file:
        contents = file.read()
        if string not in contents:
            with open(bash_file, "a") as file:
                file.write("\n{}\n".format(string))
                print("write for: {}".format(string))

print("Exporting Unreal path...")
write_string(export_ue4_root, bash_profile)
print("Export Synthetic Path...")
write_string(export_synthetic, bash_profile)

print("Done! Please execute source ~/.bashrc to load new configuration")
